### ISSUE TITLE
Hide "G" hint from interaction UI prompts

### ISSUE THREAD

**Issue by iwanPlays** [0xSmilingLizard/Receiver2Mods.ReduceUI#2]
This mod is really cool and would be even cooler, if the "G" would be hidden from hacking, light switches and item interaction hovers:
![image](https://user-images.githubusercontent.com/25465450/217647946-a4abba14-3192-4bf9-bf59-073577bc53b4.png)
![image](https://user-images.githubusercontent.com/25465450/217647992-4b98e4d9-75f3-4d42-b6ee-b1d1bec92109.png)
Unfortunately these seem to be fixed and perhaps are even controlled by presets inside Unity, as changing the keybind to spacebar or "P" doesn't change the hint letter, it stays "G".

However, with dnspy I was able to get rid of it for items and switches by adding

				this.get_help_text.alpha = 0;

into LocalAimHandler (near where 

				this.get_help_text.alpha =

gets modified)

![image](https://user-images.githubusercontent.com/25465450/217650085-6514952c-df55-45ae-946e-140f95d5b4ab.png)
![image](https://user-images.githubusercontent.com/25465450/217650102-784a0404-33fa-4d92-9239-ae4d6bb186bf.png)

And with 

			this.text.alpha = 0;

in HackingMinigame, around the end of Update(), I was able to get rid of it over turrets/cams:

![image](https://user-images.githubusercontent.com/25465450/217650464-130a737a-522b-42db-8308-765d1f4fd53b.png)

Perhaps it's easy enough to integrate this into this mod after all.

**Comment by 0xSmilingLizard** [comment]
Sorry for missing this!
I added a new release that implements this. Thank you for the (in hindsight excellent) suggestion and the info helped a lot!
